# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "parallel"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: # Mixer becomes None

name: "att_iql"

# --- Agent parameters ---
agent: "att_rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
attn_hidden_dim: 64 # Size of hidden state for attention layer
attn_n_heads: 1 # number of attention head
attn_n_layers: 1
obs_agent_id: False # For attention
obs_last_action: False # For attention
obs_use_scheme: True # For attention