env: spread

env_args:
  n_agents: 3
  seed: null
  obs_last_action: True

runner: parallel
batch_size_run: 8
test_greedy: True
test_nepisode: 100
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
save_model_interval: 50000

expr_name: spread